#!/bin/bash

set -x
set -e

rm -rf export
mkdir export

cp -r html export

(cd lane_gba && cargo build --release)

cd export || exit

arm-none-eabi-objcopy -O binary ../lane_gba/target/thumbv4t-none-eabi/release/lane "Lane_jam.gba"
gbafix -p -tLANE -cLANE -mGC "Lane_jam.gba" 

cp "Lane_jam.gba" html/game.gba

(cd html || return && zip -r ../html.zip .)
