[package]
name = "lane_logic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agb_fixnum = "0.16"
agb_hashmap = "0.16"
slotmap = { version = "1", default-features = false }
